### ISSUE TITLE
Support for converting single project?

### ISSUE THREAD

**Issue by ravensorb** [twsouthwick/NuGetPackageConfigConverter#8] opened 2016-10-21 12:30 UTC
### Installed product versions
- Visual Studio: 2015 Enterprise w/Update 3
- This extension: 1.4.3
### Description

It seems this add-in only works at the solution level currently.  It would be great it I could convert a single project if needed (example: I add a new project to the solution and want to convert just that one project)

**Comment by twsouthwick** [comment] 2016-10-31 20:49
The main reason is because then you can get into a state where you have both packages.config and project.json. If you run it for the solution, it only affects the projects that it needs to. Is that sufficient or are you really wanting to only add it to one project and leave others with packages.config?

**Comment by twsouthwick** [comment] 2016-11-08 16:46
I'll close this for now since the current work flow is by design, but please let me know if you would still prefer a single project option (or better yet, submit the PR :))

**Closed as completed by twsouthwick** 2016-11-08 16:46 UTC
