### ISSUE TITLE
Failure to upgrade

### ISSUE THREAD

**Issue by dgehri** [twsouthwick/NuGetPackageConfigConverter#22] opened 2017-11-20 21:20 UTC
### Installed product versions
- Visual Studio: 2017 Professional
- This extension: 0.1.30
- Project types within the solution being converted: C++, WiX

### Description
System.AggregateException: One or more errors occurred. ---> System.NotImplementedException: Not implemented (Exception from HRESULT: 0x80004001 (E_NOTIMPL))
   at EnvDTE.Project.get_FullName()
   at NuGetPackageConfigConverter.VSExtensions.<GetProjects>d__1.MoveNext() in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\VSExtensions.cs:line 25
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NuGetPackageConfigConverter.PackageManagerConverter.<>c__DisplayClass7_0.<ConvertAsync>b__0(ConverterUpdateViewModel model, CancellationToken token) in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\PackageManagerConverter.cs:line 47
   at NuGetPackageConfigConverter.DialogWindowConverterViewProvider.<>c__DisplayClass0_2.<ShowAsync>b__0() in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\DialogWindowConverterViewProvider.cs:line 37
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.NotImplementedException: Not implemented (Exception from HRESULT: 0x80004001 (E_NOTIMPL))
   at EnvDTE.Project.get_FullName()
   at NuGetPackageConfigConverter.VSExtensions.<GetProjects>d__1.MoveNext() in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\VSExtensions.cs:line 25
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NuGetPackageConfigConverter.PackageManagerConverter.<>c__DisplayClass7_0.<ConvertAsync>b__0(ConverterUpdateViewModel model, CancellationToken token) in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\PackageManagerConverter.cs:line 47
   at NuGetPackageConfigConverter.DialogWindowConverterViewProvider.<>c__DisplayClass0_2.<ShowAsync>b__0() in C:\projects\nugetpackageconfigconverter\src\NuGetPackageConfigConverter\Services\DialogWindowConverterViewProvider.cs:line 37<---

### Steps to recreate
1. Opened solution
2. Right-click on solution, and selected Upgrade to package references.

**Comment by twsouthwick** [comment] 2017-12-01 20:43
Fix #18

**Comment by twsouthwick** [comment] 2017-12-01 20:43
Duplicate of #18

**Closed as completed** 2017-12-01 20:43 UTC
